name: news_brief
description: "App giving information about moto."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  get_it: ^7.7.0
  talker: ^4.4.1
  talker_flutter: ^4.4.1
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  talker_dio_logger: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/